#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlgeTiles.Resource", IsApplication=true)]

namespace AlgeTiles
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int tileType = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drag = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drag_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drag_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notok = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ok = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int one = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int remove = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int remove_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int remove_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rotate = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rotate_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int rotate_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int shape = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int shape_droptarget = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int tile_1 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int tvBackground = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int unavailable = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int x = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int x2_tile = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int x_tile = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int x_tile_rot = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int xy = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int xy_tile = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int xy_tile_rot = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int y = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int y2_tile = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int y_tile = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int y_tile_rot = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int check_button = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int drag = 2131099662;
			
			// aapt resource value: 0x7f06001f
			public const int factor_button = 2131099679;
			
			// aapt resource value: 0x7f060032
			public const int image = 2131099698;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayout1 = 2131099678;
			
			// aapt resource value: 0x7f060006
			public const int lowerLeft = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int lowerMiddle = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int lowerRight = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int middleLeft = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int middleMiddle = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int middleRight = 2131099653;
			
			// aapt resource value: 0x7f060021
			public const int multiply_button = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int mute = 2131099677;
			
			// aapt resource value: 0x7f06001b
			public const int new_question_button = 2131099675;
			
			// aapt resource value: 0x7f060030
			public const int nonRotatingTiles = 2131099696;
			
			// aapt resource value: 0x7f060013
			public const int notRotatedButtonLayout = 2131099667;
			
			// aapt resource value: 0x7f060027
			public const int one_value = 2131099687;
			
			// aapt resource value: 0x7f06000b
			public const int one_value_1 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int one_value_2 = 2131099661;
			
			// aapt resource value: 0x7f060020
			public const int one_variable_button = 2131099680;
			
			// aapt resource value: 0x7f060012
			public const int refresh_button = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int remove = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int result = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int rotate = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int rotatedButtonLayout = 2131099671;
			
			// aapt resource value: 0x7f060028
			public const int sv = 2131099688;
			
			// aapt resource value: 0x7f060014
			public const int tile_1 = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int tile_1_rot = 2131099672;
			
			// aapt resource value: 0x7f06001c
			public const int tutorial = 2131099676;
			
			// aapt resource value: 0x7f060022
			public const int two_variable_button = 2131099682;
			
			// aapt resource value: 0x7f060000
			public const int upperLeft = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int upperMiddle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int upperRight = 2131099650;
			
			// aapt resource value: 0x7f060024
			public const int x2TV = 2131099684;
			
			// aapt resource value: 0x7f060016
			public const int x2_tile = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int x2_tile_rot = 2131099674;
			
			// aapt resource value: 0x7f060023
			public const int x2_value = 2131099683;
			
			// aapt resource value: 0x7f060026
			public const int xTV = 2131099686;
			
			// aapt resource value: 0x7f060015
			public const int x_tile = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int x_tile_rot = 2131099673;
			
			// aapt resource value: 0x7f060025
			public const int x_value = 2131099685;
			
			// aapt resource value: 0x7f06000a
			public const int x_value_1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int x_value_2 = 2131099660;
			
			// aapt resource value: 0x7f06002d
			public const int xy_tile = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int xy_tile_rot = 2131099695;
			
			// aapt resource value: 0x7f06002a
			public const int xy_value = 2131099690;
			
			// aapt resource value: 0x7f060031
			public const int y2_tile = 2131099697;
			
			// aapt resource value: 0x7f060029
			public const int y2_value = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int y_tile = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int y_tile_rot = 2131099694;
			
			// aapt resource value: 0x7f06002b
			public const int y_value = 2131099691;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Factor = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Multiply = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MultiplyTwoVar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int tutorial_page = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int correct = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int wrong = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int Factor = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Multiply = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int check = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int drag = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int newQ = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int oneVar = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int refresh = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int remove = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int rotate = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int twoVar = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AlgeTilesTextView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int AlgeTilesTextView_tileType = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
