#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlgeTiles.Resource", IsApplication=true)]

namespace AlgeTiles
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drag = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drag_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drag_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int remove = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int remove_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int remove_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rotate = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rotate_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rotate_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int shape = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int shape_droptarget = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tile_1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int x2_tile = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int x_tile = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int xy_tile = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int y2_tile = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int y_tile = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int drag = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int editText1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int editText2 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int editText3 = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout2 = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int lowerLeft = 2131034123;
			
			// aapt resource value: 0x7f050017
			public const int lowerMiddle = 2131034135;
			
			// aapt resource value: 0x7f05000c
			public const int lowerRight = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int middleLeft = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int middleMiddle = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int middleRight = 2131034134;
			
			// aapt resource value: 0x7f05000e
			public const int remove = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int result = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int rotate = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int space1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int space2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int space3 = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int textView2 = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int tile_1 = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int upperLeft = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int upperMiddle = 2131034131;
			
			// aapt resource value: 0x7f05000a
			public const int upperRight = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int x2_tile = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int x_tile = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Factory = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
